services:
    web_server:
        build: .
        ports:
            - "5001:5000"
        depends_on:
            - db
        environment:
            MONGODB_HOSTNAME: db
            PORT: 5000
            DEBUG: "True"
    db:
        image: mongo:latest
        ports:
            - "5002:27017"